# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-06-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployrecord',
            name='cacheDetail',
            field=models.TextField(blank=True, max_length=1024, verbose_name='修改缓存详情'),
        ),
        migrations.AlterField(
            model_name='deployrecord',
            name='isModifyCache',
            field=models.IntegerField(choices=[(0, '未修改'), (1, '修改')], default=0, verbose_name='是否修改缓存'),
        ),
        migrations.AlterField(
            model_name='deployrecord',
            name='isModifySql',
            field=models.IntegerField(choices=[(0, '未修改'), (1, '修改')], default=0, verbose_name='是否修改数据库'),
        ),
        migrations.AlterField(
            model_name='deployrecord',
            name='sqlDetail',
            field=models.TextField(blank=True, max_length=10240, verbose_name='修改数据库详情'),
        ),
    ]
