# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-08-27 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20200726_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployrecord',
            name='remark',
            field=models.TextField(default='', max_length=5120, verbose_name='增加备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuerecord',
            name='title',
            field=models.TextField(default=2, verbose_name='内容标题'),
            preserve_default=False,
        ),
    ]
