# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-08-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.CharField(max_length=100, verbose_name='实例id')),
                ('instanceName', models.CharField(max_length=200, verbose_name='实例名称')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('regionId', models.CharField(max_length=100, verbose_name='所属region')),
                ('zoneId', models.CharField(max_length=100, verbose_name='所属可用区')),
                ('instanceType', models.CharField(max_length=100, verbose_name='实例类型')),
                ('instanceChargeType', models.IntegerField(verbose_name='付费类型 包年包月-PrePaid-0  按量付费-postpaid-1')),
                ('osType', models.IntegerField(verbose_name='系统类型 0-windows 1-linux 2-ubuntu')),
                ('osName', models.CharField(max_length=200, verbose_name='系统名称')),
                ('cpu', models.IntegerField(verbose_name='cpu个数')),
                ('memory', models.IntegerField(verbose_name='内存大小')),
                ('ipType', models.IntegerField(verbose_name='ip类型 0-经典ip 1-弹性ip')),
                ('publicIp', models.GenericIPAddressField(verbose_name='公网IP')),
                ('privateIp', models.GenericIPAddressField(verbose_name='内网IP')),
                ('macAddress', models.GenericIPAddressField(verbose_name='内网macIP')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='assetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='主机组名称')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='备注名称')),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.CharField(max_length=200, unique=True, verbose_name='regionid')),
                ('regionEndpoint', models.CharField(max_length=200, verbose_name='regionEndpoint')),
                ('localName', models.CharField(max_length=200, verbose_name='localName')),
                ('humanName', models.CharField(blank=True, max_length=200, verbose_name='可读性高')),
            ],
        ),
    ]
