# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-09-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='productCode',
            field=models.CharField(default='', max_length=100, verbose_name='产品明细code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='productDetail',
            field=models.CharField(max_length=100, verbose_name='产品明细'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='所属region'),
        ),
    ]
