"""
Django settings for MidPlatform project.

Generated by 'django-admin startproject' using Django 1.11.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u=+6nn0k(!%kv-x+vepfw3z_)tf7@dxu0%x1q+ttz3*hgqf66c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


###解决跨域问题
# 此选项要打开 否则后面获取用户真实IP 无法获取
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'domains.apps.DomainsConfig',
    'component.apps.ComponentConfig',
    'deploy.apps.DeployConfig',
    'project.apps.ProjectConfig',
    'sysconf.apps.SysconfConfig',
    'mophealth.apps.MophealthConfig',

]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'midplatform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'midplatform.wsgi.application'


# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOW_CREDENTIALS = True




# CORS_ORIGIN_ALLOW_ALL = True

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'midplatform',
        'USER':'root',
        'HOST':'192.168.1.5',
        'PASSWORD':'123Moppo!@#',
        'PORT':3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True
USE_TZ = False
# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]



###自定义设置
# 与前端layui返回数据格式
RESULT = {"code":None,"msg":None,"count":None,"data":[]}

finalData= {'code': None, 'msg': None, 'data': None}

###自定义状态码以及message信息

codeMsg = {
    2001: '成功',
    2002: '两次输入密码不一致',
    2003: '用户不存在',
    20031: '用户已存在',
    20032: '请重新登陆',
    2004: '密码错误',
    2005: '用户未登陆',
    2006: '主键重复',
    2007: '请求域名接口失败，稍后再试',
    2008: '请求域名，无任何解析',
    2009: '失败',
    20091: '重复提交',
}


### 登陆成功返回字典
loginDic = {
    'access_token':None,
    'expires_in':None,
    'permissions': None,
    'info': None,
    'roles':None
}



userDefaultPassword='Moppo123'


###文件上传最大size限制
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800





