# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-05-26 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=500, verbose_name='项目名称')),
                ('project_type', models.CharField(max_length=200, verbose_name='项目类型')),
                ('website_url', models.CharField(max_length=350, verbose_name='项目地址')),
                ('gologin', models.BooleanField(verbose_name='是否可以登录')),
                ('remarks', models.CharField(max_length=300, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='projectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200, verbose_name='项目名称')),
                ('projectHook', models.CharField(max_length=200, verbose_name='项目Hook')),
                ('projectModel', models.CharField(max_length=500, verbose_name='项目模块')),
                ('projectLogo', models.CharField(max_length=500, verbose_name='项目logo地址')),
                ('status', models.IntegerField(choices=[(0, '停用'), (1, '正常')], verbose_name='使用状态')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
