# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-07-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=200, verbose_name='资产组')),
                ('group', models.CharField(max_length=200, verbose_name='资产组')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='hostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.CharField(max_length=200, verbose_name='实例ID')),
                ('InstanceName', models.CharField(blank=True, max_length=200, verbose_name='主机别名')),
                ('osType', models.IntegerField(verbose_name='系统类型 0- linux 1- windows 2- ubuntu')),
                ('ipAddress', models.CharField(blank=True, max_length=200, verbose_name='主机公网IP')),
                ('status', models.CharField(max_length=100, verbose_name='实例状态')),
                ('osName', models.CharField(max_length=100, verbose_name='系统类型')),
                ('cpu', models.IntegerField(verbose_name='cpu数量')),
                ('memory', models.IntegerField(verbose_name='内存大小')),
                ('instanceNetworkType', models.IntegerField(verbose_name='网络类型 0-vpc网络 1-经典网络')),
                ('instanceType', models.CharField(max_length=200, verbose_name='实例类型')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='projectname',
            name='projectOwner',
            field=models.CharField(default='', max_length=500, verbose_name='项目经理'),
            preserve_default=False,
        ),
    ]
