# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-07-22 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200717_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectname',
            name='projectOwnerId',
            field=models.CharField(default='', max_length=500, verbose_name='项目经理用户Id'),
            preserve_default=False,
        ),
    ]
