# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-07-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectname_projectownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectname',
            name='opsOwner',
            field=models.CharField(blank=True, max_length=500, verbose_name='运维用户'),
        ),
        migrations.AddField(
            model_name='projectname',
            name='opsOwnerId',
            field=models.CharField(blank=True, max_length=500, verbose_name='运维用户Id'),
        ),
    ]
