# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-11-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='configinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField(verbose_name='所属层级')),
                ('versioncode', models.IntegerField(unique=True, verbose_name='配置版本号')),
                ('versionname', models.CharField(max_length=20, verbose_name='配置版本名称')),
                ('content', models.TextField(verbose_name='文件内容')),
                ('iscurversion', models.BooleanField(default=False, verbose_name='是否是当前版本')),
                ('author', models.CharField(max_length=200, verbose_name='创建者')),
                ('lastauthor', models.CharField(max_length=200, verbose_name='最后一次修改者')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='configTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='名称')),
                ('parentId', models.IntegerField(verbose_name='父节点')),
                ('hierarchy', models.CharField(max_length=30, verbose_name='层级关系')),
                ('sort', models.IntegerField(verbose_name='排序值')),
                ('author', models.CharField(max_length=200, verbose_name='创建者')),
                ('description', models.CharField(max_length=500, verbose_name='描述信息')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
