# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-11-29 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansibletower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtree',
            name='depth',
            field=models.IntegerField(default='', verbose_name='深度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configtree',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='描述信息'),
        ),
    ]
