# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-12-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansibletower', '0002_auto_20201129_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configinfo',
            name='parentId',
            field=models.CharField(max_length=20, verbose_name='所属层级'),
        ),
    ]
