# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-05-30 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sys_user',
            name='type',
            field=models.IntegerField(default='', max_length=100, verbose_name='0-超级管理员，1-管理员，2-项目管理员，3-开发人员，4-测试人员，5-访客'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sys_menu',
            name='type',
            field=models.IntegerField(choices=[(0, '菜单'), (1, '按钮')], default=0, verbose_name='菜单类型 （0-目录 1-菜单 2-按钮'),
        ),
    ]
