# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-05-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0002_auto_20200530_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='type',
            field=models.IntegerField(verbose_name='0-超级管理员，1-管理员，2-项目管理员，3-开发人员，4-测试人员，5-访客'),
        ),
    ]
