# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-06-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0003_auto_20200530_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='deleted',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'deleted')], db_index=True, default=0, verbose_name='删除状态，锁定 正常'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='type',
            field=models.IntegerField(default=5, verbose_name='0-超级管理员，1-管理员，2-项目管理员，3-开发人员，4-测试人员，5-访客'),
        ),
    ]
