# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-06-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sysconf', '0004_auto_20200602_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_role',
            name='deleted',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'deleted')], db_index=True, default=0, verbose_name='删除状态，锁定 正常'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='password',
            field=mirage.fields.EncryptedCharField(max_length=500, null=True, verbose_name='显示名称'),
        ),
    ]
