# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-06-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField(db_index=True, verbose_name='任务id')),
                ('taskProject', models.CharField(max_length=50, verbose_name='监控任务所属项目')),
                ('taskName', models.CharField(max_length=50, verbose_name='监控任务名称')),
                ('taskType', models.CharField(db_index=True, max_length=5, verbose_name='任务类型：0- 服务状态，1- 业务状态')),
                ('responseTime', models.CharField(max_length=10, verbose_name='响应时间')),
                ('preResult', models.CharField(blank=True, max_length=20, verbose_name='上一次响应结果')),
                ('curResult', models.CharField(blank=True, max_length=20, verbose_name='当前响应结果')),
                ('responseResult', models.CharField(max_length=20, verbose_name='响应结果')),
                ('errorNum', models.IntegerField(default=0, verbose_name='异常次数 前端 不断更新')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='taskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskProject', models.CharField(max_length=500, verbose_name='监控任务所属项目')),
                ('taskName', models.CharField(max_length=500, verbose_name='监控任务名称')),
                ('taskUrl', models.CharField(max_length=500, verbose_name='监控任务地址')),
                ('taskType', models.CharField(db_index=True, max_length=500, verbose_name='任务类型：0- 服务状态，1- 业务状态')),
                ('reqMethod', models.IntegerField(default=0, verbose_name='请求方式0-get 1-post')),
                ('taskRate', models.IntegerField(verbose_name='执行频率 5，10, 30mins')),
                ('taskStatus', models.IntegerField(default=0, verbose_name='任务状态 0-正常，1-警告，2-致命')),
                ('alarmRule', models.IntegerField(verbose_name='0-不包含匹配内容报警 1-包含匹配内容报警')),
                ('reqBody', models.CharField(blank=True, max_length=500, verbose_name='请求体内容')),
                ('reqHeader', models.CharField(blank=True, max_length=500, verbose_name='请求头内容')),
                ('ruleContent', models.CharField(blank=True, max_length=500, verbose_name='规则内容')),
                ('responseTime', models.IntegerField(verbose_name='响应时间')),
                ('thresholdCount', models.IntegerField(default=3, verbose_name='连续几次超过阈值后报警')),
                ('deleted', models.IntegerField(default=1, verbose_name='0 删除，1 正常')),
                ('disabled', models.IntegerField(default=1, verbose_name='0 禁用，1 启用')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
