# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2020-06-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mophealth', '0002_scanlog_taskurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='disabled',
            field=models.IntegerField(default=0, verbose_name='0 禁用，1 启用'),
        ),
    ]
